In [1]:
#Importamos librer√≠as requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import io

In [ ]:
#cargar archivo csv desde equipo
from google.colab import files
files.upload()

In [3]:
#convertir en dataframe
df= pd.read_csv("CountryTable.csv")
df

,code,name,continent,region,surface_area,independence_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Willem-Alexander,129.0,AW
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
2,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,Jose Eduardo dos Santos,56.0,AO
3,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the uK,Elisabeth II,62.0,AI
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqiperia,Republic,Rexhep Mejdani,34.0,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780.0,YE
235,YuG,Yugoslavia,Europe,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,NaN,Jugoslavija,Federal Republic,Vojislav KoStunica,1792.0,Yu
236,ZAF,South Africa,Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,South Africa,Republic,Thabo Mbeki,716.0,ZA
237,ZMB,Zambia,Africa,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162.0,ZM
238,ZWE,Zimbabwe,Africa,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068.0,ZW

In [4]:
#filtro por objeto de la columna name de la fila zimbabwe
filtro1=df[df["name"] == "Zimbabwe"]
filtro1

,code,name,continent,region,surface_area,independence_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
238,ZWE,Zimbabwe,Africa,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068.0,ZW

In [5]:
#filtro por objeto de la columna continente de la fila asia
filtro12=df[df["continent"] == "Asia"]
filtro12

,code,name,continent,region,surface_area,independence_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
7,ARE,united Arab Emirates,Asia,Middle East,83600.0,1971.0,2441000,74.1,37966.0,36846.0,Al-Imarat al- Arabiya al-Muttahida,Emirate Federation,Zayid bin Sultan al-Nahayan,65.0,AE
9,ARM,Armenia,Asia,Middle East,29800.0,1991.0,3520000,66.4,1813.0,1627.0,Hajastan,Republic,Robert KotSarjan,126.0,AM
16,AZE,Azerbaijan,Asia,Middle East,86600.0,1991.0,7734000,62.9,4127.0,4100.0,Azarbaycan,Federal Republic,Heydar aliyev,144.0,AZ
21,BGD,Bangladesh,Asia,Southern and Central Asia,143998.0,1971.0,129155000,60.2,32852.0,31966.0,Bangladesh,Republic,Shahabuddin Ahmad,150.0,BD
23,BHR,Bahrain,Asia,Middle East,694.0,1971.0,617000,73.0,6366.0,6097.0,Al-Bahrayn,Monarchy (Emirate),Hamad ibn Isa al-Khalifa,149.0,BH
32,BRN,Brunei,Asia,Southeast Asia,5765.0,1984.0,328000,73.6,11705.0,12460.0,Brunei Darussalam,Monarchy (Sultanate),Haji Hassan al-Bolkiah,538.0,BN
33,BTN,Bhutan,Asia,Southern and Central Asia,47000.0,1910.0,2124000,52.4,372.0,383.0,Druk-Yul,Monarchy,Jigme Singye Wangchuk,192.0,BT
41,CHN,China,Asia,Eastern Asia,9572900.0,-1523.0,1277558000,71.4,982268.0,917719.0,Zhongquo,People'sRepublic,Jiang Zemin,1891.0,CN
54,CYP,Cyprus,Asia,Middle East,9251.0,1960.0,754700,76.7,9333.0,8246.0,Kypros/Kibris,Republic,Glafkos Klerides,2430.0,CY
77,GEO,Georgia,Asia,Middle East,69700.0,1991.0,4968000,64.5,6064.0,5924.0,Sakartvelo,Republic,Eduard Sevardnadze,905.0,GE
92,HKG,Hong Kong,Asia,Eastern Asia,1075.0,NaN,6782000,79.5,166448.0,173610.0,Xianggang/Hong Kong,Special Administrative Region of China,Jiang Zemin,937.0,HK
98,IDN,Indonesia,Asia,Southeast Asia,1904569.0,1945.0,212107000,68.0,84982.0,215002.0,Indonesia,Republic,Abdurrahman Wahid,939.0,ID
99,IND,India,Asia,Southern and Central Asia,3287263.0,1947.0,1013662000,62.5,447114.0,430572.0,Bharat/India,Federal Republic,Kocheril Raman Narayanan,1109.0,IN
102,IRN,Iran,Asia,Southern and Central Asia,1648195.0,1906.0,67702000,69.7,195746.0,160151.0,Iran,Islamic Republic,Ali Mohammad Khatami-Ardakani,1380.0,IR
103,IRQ,Iraq,Asia,Middle East,438317.0,1932.0,23115000,66.5,11500.0,NaN,Al- Iraq,Republic,Saddam Hussein al-Takriti,1365.0,IQ
105,ISR,Israel,Asia,Middle East,21056.0,1948.0,6217000,78.6,97477.0,98577.0,Yisrael/Israil,Republic,Moshe Katzav,1450.0,IL
108,JOR,Jordan,Asia,Middle East,88946.0,1946.0,5083000,77.4,7526.0,7051.0,Al-urdunn,Constitutional Monarchy,Abdullah II,1786.0,JO
109,JPN,Japan,Asia,Eastern Asia,377829.0,-660.0,126714000,80.7,3787042.0,4192638.0,Nihon/Nippon,Constitutional Monarchy,Akihito,1532.0,JP
110,KAZ,Kazakstan,Asia,Southern and Central Asia,2724900.0,1991.0,16223000,63.2,24375.0,23383.0,Qazaqstan,Republic,Nursultan Nazarbajev,1864.0,KZ
112,KGZ,Kyrgyzstan,Asia,Southern and Central Asia,199900.0,1991.0,4699000,63.4,1626.0,1767.0,Kyrgyzstan,Republic,Askar Akajev,2253.0,KG
113,KHM,Cambodia,Asia,Southeast Asia,181035.0,1953.0,11168000,56.5,5121.0,5670.0,Kampuchea,Constitutional Monarchy,Norodom Sihanouk,1800.0,KH
116,KOR,South Korea,Asia,Eastern Asia,99434.0,1948.0,46844000,74.4,320749.0,442544.0,Taehan Minguk (Namhan),Republic,Kim Dae-jung,2331.0,KR
117,KWT,Kuwait,Asia,Middle East,17818.0,1961.0,1972000,76.1,27037.0,30373.0,Al-Kuwayt,Constitutional Monarchy (Emirate),Jabir al-Ahmad al-Jabir al-Sabah,2429.0,KW
118,LAO,Laos,Asia,Southeast Asia,236800.0,1953.0,5433000,53.1,1292.0,1746.0,Lao,Republic,Khamtay Siphandone,2432.0,LA
119,LBN,Lebanon,Asia,Middle East,10400.0,1941.0,3282000,71.3,17121.0,15129.0,Lubnan,Republic,emile Lahoud,2438.0,LB
124,LKA,Sri Lanka,Asia,Southern and Central Asia,65610.0,1948.0,18827000,71.8,15706.0,15091.0,Sri Lanka/Ilankai,Republic,Chandrika Kumaratunga,3217.0,LK
129,MAC,Macao,Asia,Eastern Asia,18.0,NaN,473000,81.6,5749.0,5940.0,Macau/Aomen,Special Administrative Region of China,Jiang Zemin,2454.0,MO
134,MDV,Maldives,Asia,Southern and Central Asia,298.0,1965.0,286000,62.2,199.0,NaN,Dhivehi Raajje/Maldives,Republic,Maumoon Abdul Gayoom,2463.0,MV
140,MMR,Myanmar,Asia,Southeast Asia,676578.0,1948.0,45611000,54.9,180375.0,171028.0,Myanma Pye,Republic,kenraali Than Shwe,2710.0,MM
141,MNG,Mongolia,Asia,Eastern Asia,1566500.0,1921.0,2662000,67.3,1043.0,933.0,Mongol uls,Republic,Natsagiin Bagabandi,2696.0,MN
149,MYS,Malaysia,Asia,Southeast Asia,329758.0,1957.0,22244000,70.8,69213.0,97884.0,Malaysia,"Constitutional Monarchy, Federation",Salahuddin Abdul Aziz Shah Alhaj,2464.0,MY
160,NPL,Nepal,Asia,Southern and Central Asia,147181.0,1769.0,23930000,57.8,4768.0,4837.0,Nepal,Constitutional Monarchy,Gyanendra Bir Bikram,2729.0,NP
163,OMN,Oman,Asia,Middle East,309500.0,1951.0,2542000,71.8,16904.0,16153.0,uman,Monarchy (Sultanate),Qabus ibn Sa id,2821.0,OM
164,PAK,Pakistan,Asia,Southern and Central Asia,796095.0,1947.0,156483000,61.1,61289.0,58549.0,Pakistan,Republic,Mohammad Rafiq Tarar,2831.0,PK
168,PHL,Philippines,Asia,Southeast Asia,300000.0,1946.0,75967000,67.5,65107.0,82239.0,Pilipinas,Republic,Gloria Macapagal-Arroyo,766.0,PH
173,PRK,North Korea,Asia,Eastern Asia,120538.0,1948.0,24039000,70.7,5332.0,NaN,Choson Minjujuui In min Konghwaguk (Bukhan),Socialistic Republic,Kim Jong-il,2318.0,KP
176,PSE,Palestine,Asia,Middle East,6257.0,NaN,3101000,71.4,4173.0,NaN,Filastin,Autonomous Area,Yasser (Yasir) Arafat,4074.0,PS
178,QAT,Qatar,Asia,Middle East,11000.0,1971.0,599000,72.4,9472.0,8920.0,Qatar,Monarchy,Hamad ibn Khalifa al-Thani,2973.0,QA
183,SAu,Saudi Arabia,Asia,Middle East,2149690.0,1932.0,21607000,67.8,137635.0,146171.0,Al- Arabiya as-Sa udiya,Monarchy,Fahd ibn Abdul-Aziz al-Sa ud,3173.0,SA
186,SGP,Singapore,Asia,Southeast Asia,618.0,1965.0,3567000,80.1,86503.0,96318.0,Singapore/Singapura/Xinjiapo/Singapur,Republic,Sellapan Rama Nathan,3208.0,SG
203,SYR,Syria,Asia,Middle East,185180.0,1941.0,16125000,68.5,65984.0,64926.0,Suriya,Republic,Bashar al-Assad,3250.0,SY
207,THA,Thailand,Asia,Southeast Asia,513115.0,1350.0,61399000,68.6,116416.0,153907.0,Prathet Thai,Constitutional Monarchy,Bhumibol Adulyadej,3320.0,TH
208,TJK,Tajikistan,Asia,Southern and Central Asia,143100.0,1991.0,6188000,64.1,1990.0,1056.0,Tocikiston,Republic,Emomali Rahmonov,3261.0,TJ
210,TKM,Turkmenistan,Asia,Southern and Central Asia,488100.0,1991.0,4459000,60.9,4397.0,2000.0,Turkmenostan,Republic,Saparmurad Nijazov,3419.0,TM
211,TMP,East Timor,Asia,Southeast Asia,14874.0,NaN,885000,46.0,0.0,NaN,Timor Timur,Administrated by the uN,Jose Alexandre Gusmao,1522.0,TP
215,TuR,Turkey,Asia,Middle East,774815.0,1923.0,66591000,71.0,210721.0,189122.0,Turkiye,Republic,Ahmet Necdet Sezer,3358.0,TR
217,TWN,Taiwan,Asia,Eastern Asia,36188.0,1945.0,22256000,76.4,256254.0,263451.0,Tai-wan,Republic,Chen Shui-bian,3263.0,TW
224,uZB,uzbekistan,Asia,Southern and Central Asia,447400.0,1991.0,24318000,63.7,14194.0,21300.0,uzbekiston,Republic,Islam Karimov,3503.0,uZ
230,VNM,Vietnam,Asia,Southeast Asia,331689.0,1945.0,79832000,69.3,21929.0,22834.0,Viet Nam,Socialistic Republic,Tran Duc Luong,3770.0,VN
234,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780.0,YE

In [6]:
#filtro por filas, de la fila 0 a la 200
filtro21= df.iloc[0:200, : ]
filtro21

,code,name,continent,region,surface_area,independence_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Willem-Alexander,129.0,AW
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
2,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,Jose Eduardo dos Santos,56.0,AO
3,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the uK,Elisabeth II,62.0,AI
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqiperia,Republic,Rexhep Mejdani,34.0,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,SPM,Saint Pierre and Miquelon,North America,North America,242.0,NaN,7000,77.6,0.0,NaN,Saint-Pierre-et-Miquelon,Territorial Collectivity of France,Jacques Chirac,3067.0,PM
196,STP,Sao Tome and Principe,Africa,Central Africa,964.0,1975.0,147000,65.3,6.0,NaN,Sao Tome e PrIncipe,Republic,Miguel Trovoada,3172.0,ST
197,SuR,Suriname,South America,South America,163265.0,1975.0,417000,71.4,870.0,706.0,Suriname,Republic,Ronald Venetiaan,3243.0,SR
198,SVK,Slovakia,Europe,Eastern Europe,49012.0,1993.0,5398700,73.7,20594.0,19452.0,Slovensko,Republic,Rudolf Schuster,3209.0,SK
199,SVN,Slovenia,Europe,Southern Europe,20256.0,1991.0,1987800,74.9,19756.0,18202.0,Slovenija,Republic,Milan Kucan,3212.0,SI

In [7]:
#filtro por filas. Se filtra la fila 43, 68 y 71
filtro22=df.iloc[[43, 68, 71], : ] #filas no consecutivas
filtro22

,code,name,continent,region,surface_area,independence_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
43,CMR,Cameroon,Africa,Central Africa,475442.0,1960.0,15085000,54.8,9174.0,8596.0,Cameroun/Cameroon,Republic,Paul Biya,1804.0,CM
68,ETH,Ethiopia,Africa,Eastern Africa,1104300.0,-1000.0,62565000,45.2,6353.0,6180.0,YeItyop iya,Republic,Negasso Gidada,756.0,ET
71,FLK,Falkland Islands,South America,South America,12173.0,NaN,2000,NaN,0.0,NaN,Falkland Islands,Dependent Territory of the uK,Elisabeth II,763.0,FK

In [8]:
#Filtro por columnas. Se filtro la columna 3 y 5
filtro31=df.iloc[ : , 3:5]
filtro31

                        region  surface_area
0                    Caribbean         193.0
1    Southern and Central Asia      652090.0
2               Central Africa     1246700.0
3                    Caribbean          96.0
4              Southern Europe       28748.0
..                         ...           ...
234                Middle East      527968.0
235            Southern Europe      102173.0
236            Southern Africa     1221037.0
237             Eastern Africa      752618.0
238             Eastern Africa      390757.0

[239 rows x 2 columns]

In [9]:
#Filtro por columnas
filtro32=df.iloc[ : , [1,3,5]] #columnas no consecutivas
filtro32
#Se filtraron las columnas 1, 3 y 5

             name                     region  independence_year
0           Aruba                  Caribbean                NaN
1     Afghanistan  Southern and Central Asia             1919.0
2          Angola             Central Africa             1975.0
3        Anguilla                  Caribbean                NaN
4         Albania            Southern Europe             1912.0
..            ...                        ...                ...
234         Yemen                Middle East             1918.0
235    Yugoslavia            Southern Europe             1918.0
236  South Africa            Southern Africa             1910.0
237        Zambia             Eastern Africa             1964.0
238      Zimbabwe             Eastern Africa             1980.0

[239 rows x 3 columns]

In [10]:
#filtro por columnas y por filas
filtro_mix=df.iloc[ [43,68,71] , 3:5]
filtro_mix
#Se filtraron las columnas 3 y 5; y las filas 43, 68 y 71

            region  surface_area
43  Central Africa      475442.0
68  Eastern Africa     1104300.0
71   South America       12173.0

In [11]:
#filtro por columnas y por filas
filtrofresh=df.iloc[ : , [1,3,5]] #columnas no consecutivas
filtrofresh
#se filtrearon columnas no consecutivas (1, 3 y 5)

             name                     region  independence_year
0           Aruba                  Caribbean                NaN
1     Afghanistan  Southern and Central Asia             1919.0
2          Angola             Central Africa             1975.0
3        Anguilla                  Caribbean                NaN
4         Albania            Southern Europe             1912.0
..            ...                        ...                ...
234         Yemen                Middle East             1918.0
235    Yugoslavia            Southern Europe             1918.0
236  South Africa            Southern Africa             1910.0
237        Zambia             Eastern Africa             1964.0
238      Zimbabwe             Eastern Africa             1980.0

[239 rows x 3 columns]

In [ ]:
#Filtro de filas vs columnas
#Paso 1: Leemos el contenido del archivo
from google.colab import files
uploaded=files.upload()
df=pd.read_csv(io.BytesIO(uploaded['CountryTable.csv']), index_col=3)
df

In [13]:
#Filtro de filas vs columnas
#Paso 1: Leemos el contenido del archivo
from google.colab import files
uploaded=files.upload()
df=pd.read_csv(io.BytesIO(uploaded['CountryTable.csv']), index_col=1)
df
#Paso 2: Aplicamos filtro de filas vs columnas
filtro4=df.loc[["Aruba","Angola"], ["region"]]
filtro4
#Filtramos Aruba y Angola de filas y en columnas la region

Saving CountryTable.csv to CountryTable (2).csv

                region
name
Aruba        Caribbean
Angola  Central Africa

In [14]:
#Filtro por cabecera
filtro51=df.head(4)
filtro51
#Filtramos los primeros cuatro datos

,code,continent,region,surface_area,independence_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
name,,,,,,,,,,,,,,
Aruba,ABW,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Willem-Alexander,129.0,AW
Afghanistan,AFG,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
Angola,AGO,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,Jose Eduardo dos Santos,56.0,AO
Anguilla,AIA,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the uK,Elisabeth II,62.0,AI

In [15]:
#Filtro por cabecera
filtro52=df.head(3)
filtro52
#filtramos los primeros tres datos de la tabla

,code,continent,region,surface_area,independence_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
name,,,,,,,,,,,,,,
Aruba,ABW,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Willem-Alexander,129.0,AW
Afghanistan,AFG,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
Angola,AGO,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,Jose Eduardo dos Santos,56.0,AO

In [16]:
#Filtro por comparacion
filtro61=df[df["continent"] == "Africa"]
filtro61
#filtramos la columna de continente para solo obtener la de Africa

,code,continent,region,surface_area,independence_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
name,,,,,,,,,,,,,,
Angola,AGO,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,Jose Eduardo dos Santos,56.0,AO
Burundi,BDI,Africa,Eastern Africa,27834.0,1962.0,6695000,46.2,903.0,982.0,Burundi/uburundi,Republic,Pierre Buyoya,552.0,BI
Benin,BEN,Africa,Western Africa,112622.0,1960.0,6097000,50.2,2357.0,2141.0,Benin,Republic,Mathieu Kerekou,187.0,BJ
Burkina Faso,BFA,Africa,Western Africa,274000.0,1960.0,11937000,46.7,2425.0,2201.0,Burkina Faso,Republic,Blaise Compaore,549.0,BF
Botswana,BWA,Africa,Southern Africa,581730.0,1966.0,1622000,39.3,4834.0,4935.0,Botswana,Republic,Festus G. Mogae,204.0,BW
Central African Republic,CAF,Africa,Central Africa,622984.0,1960.0,3615000,44.0,1054.0,993.0,Centrafrique/Be-Afrika,Republic,Ange-Felix Patasse,1889.0,CF
Cote dIvoire,CIV,Africa,Western Africa,322463.0,1960.0,14786000,45.2,11345.0,10285.0,Cote dIvoire,Republic,Laurent Gbagbo,2814.0,CI
Cameroon,CMR,Africa,Central Africa,475442.0,1960.0,15085000,54.8,9174.0,8596.0,Cameroun/Cameroon,Republic,Paul Biya,1804.0,CM
"Congo, The Democratic Republic of the",COD,Africa,Central Africa,2344858.0,1960.0,51654000,48.8,6964.0,2474.0,Republique Democratique du Congo,Republic,Joseph Kabila,2298.0,CD
Congo,COG,Africa,Central Africa,342000.0,1960.0,2943000,47.4,2108.0,2287.0,Congo,Republic,Denis Sassou-Nguesso,2296.0,CG
Comoros,COM,Africa,Eastern Africa,1862.0,1975.0,578000,60.0,4401.0,4361.0,Komori/Comores,Republic,Azali Assoumani,2295.0,KM
Cape Verde,CPV,Africa,Western Africa,4033.0,1975.0,428000,68.9,435.0,420.0,Cabo Verde,Republic,Antonio Mascarenhas Monteiro,1859.0,CV
Djibouti,DJI,Africa,Eastern Africa,23200.0,1977.0,638000,50.8,382.0,373.0,Djibouti/Jibuti,Republic,Ismail Omar Guelleh,585.0,DJ
Algeria,DZA,Africa,Northern Africa,2381741.0,1962.0,31471000,69.7,49982.0,46966.0,Al-Jazair/Algerie,Republic,Abdelaziz Bouteflika,35.0,DZ
Egypt,EGY,Africa,Northern Africa,1001449.0,1922.0,68470000,63.3,82710.0,75617.0,Misr,Republic,Hosni Mubarak,608.0,EG
Eritrea,ERI,Africa,Eastern Africa,117600.0,1993.0,3850000,55.8,650.0,755.0,Ertra,Republic,Isayas Afewerki [Isaias Afwerki],652.0,ER
Western Sahara,ESH,Africa,Northern Africa,266000.0,NaN,293000,49.8,60.0,NaN,As-Sahrawiya,Occupied by Marocco,Mohammed Abdel Aziz,2453.0,EH
Ethiopia,ETH,Africa,Eastern Africa,1104300.0,-1000.0,62565000,45.2,6353.0,6180.0,YeItyop iya,Republic,Negasso Gidada,756.0,ET
Gabon,GAB,Africa,Central Africa,267668.0,1960.0,1226000,50.1,5493.0,5279.0,Le Gabon,Republic,Omar Bongo,902.0,GA
Ghana,GHA,Africa,Western Africa,238533.0,1957.0,20212000,57.4,7137.0,6884.0,Ghana,Republic,John Kufuor,910.0,GH
Guinea,GIN,Africa,Western Africa,245857.0,1958.0,7430000,45.6,2352.0,2383.0,Guinee,Republic,Lansana Conte,926.0,GN
Gambia,GMB,Africa,Western Africa,11295.0,1965.0,1305000,53.2,320.0,325.0,The Gambia,Republic,Yahya Jammeh,904.0,GM
Guinea-Bissau,GNB,Africa,Western Africa,36125.0,1974.0,1213000,49.0,293.0,272.0,Guine-Bissau,Republic,Kumba Iala,927.0,GW
Equatorial Guinea,GNQ,Africa,Central Africa,28051.0,1968.0,453000,53.6,283.0,542.0,Guinea Ecuatorial,Republic,Teodoro Obiang Nguema Mbasogo,2972.0,GQ
British Indian Ocean Territory,IOT,Africa,Eastern Africa,78.0,NaN,0,NaN,0.0,NaN,British Indian Ocean Territory,Dependent Territory of the uK,Elisabeth II,NaN,IO
Kenya,KEN,Africa,Eastern Africa,580367.0,1963.0,30080000,48.0,9217.0,10241.0,Kenya,Republic,Daniel arap Moi,1881.0,KE
Liberia,LBR,Africa,Western Africa,111369.0,1847.0,3154000,51.0,2012.0,NaN,Liberia,Republic,Charles Taylor,2440.0,LR
Libyan Arab Jamahiriya,LBY,Africa,Northern Africa,1759540.0,1951.0,5605000,75.5,44806.0,40562.0,Libiya,Socialistic State,Muammar al-Qadhafi,2441.0,LY
Lesotho,LSO,Africa,Southern Africa,30355.0,1966.0,2153000,50.8,1061.0,1161.0,Lesotho,Constitutional Monarchy,Letsie III,2437.0,LS
Morocco,MAR,Africa,Northern Africa,446550.0,1956.0,28351000,69.1,36124.0,33514.0,Al-Maghrib,Constitutional Monarchy,Mohammed VI,2486.0,MA
Madagascar,MDG,Africa,Eastern Africa,587041.0,1960.0,15942000,55.0,3750.0,3545.0,Madagasikara/Madagascar,Federal Republic,Didier Ratsiraka,2455.0,MG
Mali,MLI,Africa,Western Africa,1240192.0,1960.0,11234000,46.7,2642.0,2453.0,Mali,Republic,Alpha Oumar Konare,2482.0,ML
Mozambique,MOZ,Africa,Eastern Africa,801590.0,1975.0,19680000,37.5,2891.0,2711.0,Mocambique,Republic,JoaquIm A. Chissano,2698.0,MZ
Mauritania,MRT,Africa,Western Africa,1025520.0,1960.0,2670000,50.8,998.0,1081.0,Muritaniya/Mauritanie,Republic,Maaouiya Ould Sid Ahmad Taya,2509.0,MR
Mauritius,MuS,Africa,Eastern Africa,2040.0,1968.0,1158000,71.0,4251.0,4186.0,Mauritius,Republic,Cassam uteem,2511.0,Mu
Malawi,MWI,Africa,Eastern Africa,118484.0,1964.0,10925000,37.6,1687.0,2527.0,Malawi,Republic,Bakili Muluzi,2462.0,MW
Mayotte,MYT,Africa,Eastern Africa,373.0,NaN,149000,59.5,0.0,NaN,Mayotte,Territorial Collectivity of France,Jacques Chirac,2514.0,YT
Namibia,NAM,Africa,Southern Africa,824292.0,1990.0,1726000,42.5,3101.0,3384.0,Namibia,Republic,Sam Nujoma,2726.0,NaN
Niger,NER,Africa,Western Africa,1267000.0,1960.0,10730000,41.3,1706.0,1580.0,Niger,Republic,Mamadou Tandja,2738.0,NE
Nigeria,NGA,Africa,Western Africa,923768.0,1960.0,111506000,51.6,65707.0,58623.0,Nigeria,Federal Republic,Olusegun Obasanjo,2754.0,NG
Reunion,REu,Africa,Eastern Africa,2510.0,NaN,699000,72.7,8287.0,7988.0,Reunion,Overseas Department of France,Jacques Chirac,3017.0,RE
Rwanda,RWA,Africa,Eastern Africa,26338.0,1962.0,7733000,39.3,2036.0,1863.0,Rwanda/urwanda,Republic,Paul Kagame,3047.0,RW
Sudan,SDN,Africa,Northern Africa,2505813.0,1956.0,29490000,56.6,10162.0,NaN,As-Sudan,Islamic Republic,Omar Hassan Ahmad al-Bashir,3225.0,SD
Senegal,SEN,Africa,Western Africa,196722.0,1960.0,9481000,62.2,4787.0,4542.0,Senegal/Sounougal,Republic,Abdoulaye Wade,3198.0,SN
Saint Helena,SHN,Africa,Western Africa,314.0,NaN,6000,76.8,0.0,NaN,Saint Helena,Dependent Territory of the uK,Elisabeth II,3063.0,SH
Sierra Leone,SLE,Africa,Western Africa,71740.0,1961.0,4854000,45.3,746.0,858.0,Sierra Leone,Republic,Ahmed Tejan Kabbah,3207.0,SL
Somalia,SOM,Africa,Eastern Africa,637657.0,1960.0,10097000,46.2,935.0,NaN,Soomaaliya,Republic,Abdiqassim Salad Hassan,3214.0,SO
Sao Tome and Principe,STP,Africa,Central Africa,964.0,1975.0,147000,65.3,6.0,NaN,Sao Tome e PrIncipe,Republic,Miguel Trovoada,3172.0,ST
Swaziland,SWZ,Africa,Southern Africa,17364.0,1968.0,1008000,40.4,1206.0,1312.0,kaNgwane,Monarchy,Mswati III,3244.0,SZ
Seychelles,SYC,Africa,Eastern Africa,455.0,1976.0,77000,70.4,536.0,539.0,Sesel/Seychelles,Republic,France-Albert Rene,3206.0,SC
Chad,TCD,Africa,Central Africa,1284000.0,1960.0,7651000,50.5,1208.0,1102.0,Tchad/Tshad,Republic,Idriss Deby,3337.0,TD
Togo,TGO,Africa,Western Africa,56785.0,1960.0,4629000,54.7,1449.0,1400.0,Togo,Republic,Gnassingbe Eyadema,3332.0,TG
Tunisia,TuN,Africa,Northern Africa,163610.0,1956.0,9586000,73.7,20026.0,18898.0,Tunis/Tunisie,Republic,Zine al-Abidine Ben Ali,3349.0,TN
Tanzania,TZA,Africa,Eastern Africa,883749.0,1961.0,33517000,52.3,8005.0,7388.0,Tanzania,Republic,Benjamin William Mkapa,3306.0,TZ
uganda,uGA,Africa,Eastern Africa,241038.0,1962.0,21778000,42.9,6313.0,6887.0,uganda,Republic,Yoweri Museveni,3425.0,uG
South Africa,ZAF,Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,South Africa,Republic,Thabo Mbeki,716.0,ZA
Zambia,ZMB,Africa,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162.0,ZM
Zimbabwe,ZWE,Africa,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068.0,ZW

In [18]:
#Filtro Y
filtro71=df[(df["independence_year"] == 1960) & (df["continent"] =="Africa") & (df["region"] == "Central Africa")]
filtro71
#filtramos que el a√±o de independencia sea solo para 1960 que el continente sea solo Africa y que la region solo sea para Central Africa

,code,continent,region,surface_area,independence_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
name,,,,,,,,,,,,,,
Central African Republic,CAF,Africa,Central Africa,622984.0,1960.0,3615000,44.0,1054.0,993.0,Centrafrique/Be-Afrika,Republic,Ange-Felix Patasse,1889.0,CF
Cameroon,CMR,Africa,Central Africa,475442.0,1960.0,15085000,54.8,9174.0,8596.0,Cameroun/Cameroon,Republic,Paul Biya,1804.0,CM
"Congo, The Democratic Republic of the",COD,Africa,Central Africa,2344858.0,1960.0,51654000,48.8,6964.0,2474.0,Republique Democratique du Congo,Republic,Joseph Kabila,2298.0,CD
Congo,COG,Africa,Central Africa,342000.0,1960.0,2943000,47.4,2108.0,2287.0,Congo,Republic,Denis Sassou-Nguesso,2296.0,CG
Gabon,GAB,Africa,Central Africa,267668.0,1960.0,1226000,50.1,5493.0,5279.0,Le Gabon,Republic,Omar Bongo,902.0,GA
Chad,TCD,Africa,Central Africa,1284000.0,1960.0,7651000,50.5,1208.0,1102.0,Tchad/Tshad,Republic,Idriss Deby,3337.0,TD

In [19]:
#Filtro Y
filtro72=df[(df["capital"] > 902) & (df["life_expectancy"]>50) & (df["gnp"] < 6000)]
filtro72
#Filtramos que el capital nos de solo para mayores a 902 al igual que life expentancy >50 y que GNP sea para menores de 6000

,code,continent,region,surface_area,independence_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
name,,,,,,,,,,,,,,
Comoros,COM,Africa,Eastern Africa,1862.0,1975.0,578000,60.0,4401.0,4361.0,Komori/Comores,Republic,Azali Assoumani,2295.0,KM
Cape Verde,CPV,Africa,Western Africa,4033.0,1975.0,428000,68.9,435.0,420.0,Cabo Verde,Republic,Antonio Mascarenhas Monteiro,1859.0,CV
Estonia,EST,Europe,Baltic Countries,45227.0,1991.0,1439200,69.5,5328.0,3371.0,Eesti,Republic,Lennart Meri,3791.0,EE
"Micronesia, Federated States of",FSM,Oceania,Micronesia,702.0,1990.0,119000,68.6,212.0,NaN,Micronesia,Federal Republic,Leo A. Falcam,2689.0,FM
Gibraltar,GIB,Europe,Southern Europe,6.0,NaN,25000,79.0,258.0,NaN,Gibraltar,Dependent Territory of the uK,Elisabeth II,915.0,GI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Tuvalu,TuV,Oceania,Polynesia,26.0,1978.0,12000,66.3,6.0,NaN,Tuvalu,Constitutional Monarchy,Elisabeth II,3424.0,TV
Saint Vincent and the Grenadines,VCT,North America,Caribbean,388.0,1979.0,114000,72.3,285.0,NaN,Saint Vincent and the Grenadines,Constitutional Monarchy,Elisabeth II,3066.0,VC
"Virgin Islands, u.S.",VIR,North America,Caribbean,347.0,NaN,93000,78.1,0.0,NaN,Virgin Islands of the united States,uS Territory,George W. Bush,4067.0,VI
Vanuatu,VuT,Oceania,Melanesia,12189.0,1980.0,190000,60.6,261.0,246.0,Vanuatu,Republic,John Bani,3537.0,Vu
Samoa,WSM,Oceania,Polynesia,2831.0,1962.0,180000,69.2,141.0,157.0,Samoa,Parlementary Monarchy,Malietoa Tanumafili II,3169.0,WS

In [20]:
#Filtro 8
filtro81=df[(df["continent"]== "Oceania") | (df["capital"] > 2000)]
filtro81
#Se filtraron todos los datos que fueran de oceania o que su capital fuera mayor a 2000

,code,continent,region,surface_area,independence_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
name,,,,,,,,,,,,,,
American Samoa,ASM,Oceania,Polynesia,199.0,NaN,68000,75.1,334.0,NaN,Amerika Samoa,uS Territory,George W. Bush,54.0,AS
Australia,AuS,Oceania,Australia and New Zealand,7741220.0,1901.0,18886000,79.8,351182.0,392911.0,Australia,"Constitutional Monarchy, Federation",Elisabeth II,135.0,Au
Belarus,BLR,Europe,Eastern Europe,207600.0,1991.0,10236000,68.0,13714.0,NaN,Belarus,Republic,Aljaksandr LukaSenka,3520.0,BY
Cocos (Keeling) Islands,CCK,Oceania,Australia and New Zealand,14.0,NaN,600,NaN,0.0,NaN,Cocos (Keeling) Islands,Territory of Australia,Elisabeth II,2317.0,CC
Switzerland,CHE,Europe,Western Europe,41284.0,1499.0,7160400,79.6,264478.0,256092.0,Schweiz/Suisse/Svizzera/Svizra,Federation,Adolf Ogi,3248.0,CH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Vanuatu,VuT,Oceania,Melanesia,12189.0,1980.0,190000,60.6,261.0,246.0,Vanuatu,Republic,John Bani,3537.0,Vu
Wallis and Futuna,WLF,Oceania,Polynesia,200.0,NaN,15000,NaN,0.0,NaN,Wallis-et-Futuna,Nonmetropolitan Territory of France,Jacques Chirac,3536.0,WF
Samoa,WSM,Oceania,Polynesia,2831.0,1962.0,180000,69.2,141.0,157.0,Samoa,Parlementary Monarchy,Malietoa Tanumafili II,3169.0,WS
Zambia,ZMB,Africa,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162.0,ZM
Zimbabwe,ZWE,Africa,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068.0,ZW

In [21]:
#Filtro 8
filtro82=df[(df["life_expectancy"] <50) | (df["continent"]=="Oceania")]
filtro82
#Se obtuvieron todos los datos que tuvieran una expectativa de vida menor a 50 o que fueran de ocean√≠a

,code,continent,region,surface_area,independence_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
name,,,,,,,,,,,,,,
Afghanistan,AFG,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
Angola,AGO,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,Jose Eduardo dos Santos,56.0,AO
American Samoa,ASM,Oceania,Polynesia,199.0,NaN,68000,75.1,334.0,NaN,Amerika Samoa,uS Territory,George W. Bush,54.0,AS
Australia,AuS,Oceania,Australia and New Zealand,7741220.0,1901.0,18886000,79.8,351182.0,392911.0,Australia,"Constitutional Monarchy, Federation",Elisabeth II,135.0,Au
Burundi,BDI,Africa,Eastern Africa,27834.0,1962.0,6695000,46.2,903.0,982.0,Burundi/uburundi,Republic,Pierre Buyoya,552.0,BI
Burkina Faso,BFA,Africa,Western Africa,274000.0,1960.0,11937000,46.7,2425.0,2201.0,Burkina Faso,Republic,Blaise Compaore,549.0,BF
Botswana,BWA,Africa,Southern Africa,581730.0,1966.0,1622000,39.3,4834.0,4935.0,Botswana,Republic,Festus G. Mogae,204.0,BW
Central African Republic,CAF,Africa,Central Africa,622984.0,1960.0,3615000,44.0,1054.0,993.0,Centrafrique/Be-Afrika,Republic,Ange-Felix Patasse,1889.0,CF
Cocos (Keeling) Islands,CCK,Oceania,Australia and New Zealand,14.0,NaN,600,NaN,0.0,NaN,Cocos (Keeling) Islands,Territory of Australia,Elisabeth II,2317.0,CC
Cote dIvoire,CIV,Africa,Western Africa,322463.0,1960.0,14786000,45.2,11345.0,10285.0,Cote dIvoire,Republic,Laurent Gbagbo,2814.0,CI
"Congo, The Democratic Republic of the",COD,Africa,Central Africa,2344858.0,1960.0,51654000,48.8,6964.0,2474.0,Republique Democratique du Congo,Republic,Joseph Kabila,2298.0,CD
Congo,COG,Africa,Central Africa,342000.0,1960.0,2943000,47.4,2108.0,2287.0,Congo,Republic,Denis Sassou-Nguesso,2296.0,CG
Cook Islands,COK,Oceania,Polynesia,236.0,NaN,20000,71.1,100.0,NaN,The Cook Islands,Nonmetropolitan Territory of New Zealand,Elisabeth II,583.0,CK
Christmas Island,CXR,Oceania,Australia and New Zealand,135.0,NaN,2500,NaN,0.0,NaN,Christmas Island,Territory of Australia,Elisabeth II,1791.0,CX
Western Sahara,ESH,Africa,Northern Africa,266000.0,NaN,293000,49.8,60.0,NaN,As-Sahrawiya,Occupied by Marocco,Mohammed Abdel Aziz,2453.0,EH
Ethiopia,ETH,Africa,Eastern Africa,1104300.0,-1000.0,62565000,45.2,6353.0,6180.0,YeItyop iya,Republic,Negasso Gidada,756.0,ET
Fiji Islands,FJI,Oceania,Melanesia,18274.0,1970.0,817000,67.9,1536.0,2149.0,Fiji Islands,Republic,Josefa Iloilo,764.0,FJ
"Micronesia, Federated States of",FSM,Oceania,Micronesia,702.0,1990.0,119000,68.6,212.0,NaN,Micronesia,Federal Republic,Leo A. Falcam,2689.0,FM
Guinea,GIN,Africa,Western Africa,245857.0,1958.0,7430000,45.6,2352.0,2383.0,Guinee,Republic,Lansana Conte,926.0,GN
Guinea-Bissau,GNB,Africa,Western Africa,36125.0,1974.0,1213000,49.0,293.0,272.0,Guine-Bissau,Republic,Kumba Iala,927.0,GW
Guam,GuM,Oceania,Micronesia,549.0,NaN,168000,77.8,1197.0,1136.0,Guam,uS Territory,George W. Bush,921.0,Gu
Haiti,HTI,North America,Caribbean,27750.0,1804.0,8222000,49.2,3459.0,3107.0,Haiti/Dayti,Republic,Jean-Bertrand Aristide,929.0,HT
Kenya,KEN,Africa,Eastern Africa,580367.0,1963.0,30080000,48.0,9217.0,10241.0,Kenya,Republic,Daniel arap Moi,1881.0,KE
Kiribati,KIR,Oceania,Micronesia,726.0,1979.0,83000,59.8,40.7,NaN,Kiribati,Republic,Teburoro Tito,2256.0,KI
Marshall Islands,MHL,Oceania,Micronesia,181.0,1990.0,64000,65.5,97.0,NaN,Marshall Islands/Majol,Republic,Kessai Note,2507.0,MH
Mali,MLI,Africa,Western Africa,1240192.0,1960.0,11234000,46.7,2642.0,2453.0,Mali,Republic,Alpha Oumar Konare,2482.0,ML
Northern Mariana Islands,MNP,Oceania,Micronesia,464.0,NaN,78000,75.5,0.0,NaN,Northern Mariana Islands,Commonwealth of the uS,George W. Bush,2913.0,MP
Mozambique,MOZ,Africa,Eastern Africa,801590.0,1975.0,19680000,37.5,2891.0,2711.0,Mocambique,Republic,JoaquIm A. Chissano,2698.0,MZ
Malawi,MWI,Africa,Eastern Africa,118484.0,1964.0,10925000,37.6,1687.0,2527.0,Malawi,Republic,Bakili Muluzi,2462.0,MW
Namibia,NAM,Africa,Southern Africa,824292.0,1990.0,1726000,42.5,3101.0,3384.0,Namibia,Republic,Sam Nujoma,2726.0,NaN
New Caledonia,NCL,Oceania,Melanesia,18575.0,NaN,214000,72.8,3563.0,NaN,Nouvelle-Caledonie,Nonmetropolitan Territory of France,Jacques Chirac,3493.0,NC
Niger,NER,Africa,Western Africa,1267000.0,1960.0,10730000,41.3,1706.0,1580.0,Niger,Republic,Mamadou Tandja,2738.0,NE
Norfolk Island,NFK,Oceania,Australia and New Zealand,36.0,NaN,2000,NaN,0.0,NaN,Norfolk Island,Territory of Australia,Elisabeth II,2806.0,NF
Niue,NIu,Oceania,Polynesia,260.0,NaN,2000,NaN,0.0,NaN,Niue,Nonmetropolitan Territory of New Zealand,Elisabeth II,2805.0,Nu
Nauru,NRu,Oceania,Micronesia,21.0,1968.0,12000,60.8,197.0,NaN,Naoero/Nauru,Republic,Bernard Dowiyogo,2728.0,NR
New Zealand,NZL,Oceania,Australia and New Zealand,270534.0,1907.0,3862000,77.8,54669.0,64960.0,New Zealand/Aotearoa,Constitutional Monarchy,Elisabeth II,3499.0,NZ
Pitcairn,PCN,Oceania,Polynesia,49.0,NaN,50,NaN,0.0,NaN,Pitcairn,Dependent Territory of the uK,Elisabeth II,2912.0,PN
Palau,PLW,Oceania,Micronesia,459.0,1994.0,19000,68.6,105.0,NaN,Belau/Palau,Republic,Kuniwo Nakamura,2881.0,PW
Papua New Guinea,PNG,Oceania,Melanesia,462840.0,1975.0,4807000,63.1,4988.0,6328.0,Papua New Guinea/Papua Niugini,Constitutional Monarchy,Elisabeth II,2884.0,PG
French Polynesia,PYF,Oceania,Polynesia,4000.0,NaN,235000,74.8,818.0,781.0,Polynesie francaise,Nonmetropolitan Territory of France,Jacques Chirac,3016.0,PF
Rwanda,RWA,Africa,Eastern Africa,26338.0,1962.0,7733000,39.3,2036.0,1863.0,Rwanda/urwanda,Republic,Paul Kagame,3047.0,RW
Solomon Islands,SLB,Oceania,Melanesia,28896.0,1978.0,444000,71.3,182.0,220.0,Solomon Islands,Constitutional Monarchy,Elisabeth II,3161.0,SB
Sierra Leone,SLE,Africa,Western Africa,71740.0,1961.0,4854000,45.3,746.0,858.0,Sierra Leone,Republic,Ahmed Tejan Kabbah,3207.0,SL
Somalia,SOM,Africa,Eastern Africa,637657.0,1960.0,10097000,46.2,935.0,NaN,Soomaaliya,Republic,Abdiqassim Salad Hassan,3214.0,SO
Swaziland,SWZ,Africa,Southern Africa,17364.0,1968.0,1008000,40.4,1206.0,1312.0,kaNgwane,Monarchy,Mswati III,3244.0,SZ
Tokelau,TKL,Oceania,Polynesia,12.0,NaN,2000,NaN,0.0,NaN,Tokelau,Nonmetropolitan Territory of New Zealand,Elisabeth II,3333.0,TK
East Timor,TMP,Asia,Southeast Asia,14874.0,NaN,885000,46.0,0.0,NaN,Timor Timur,Administrated by the uN,Jose Alexandre Gusmao,1522.0,TP
Tonga,TON,Oceania,Polynesia,650.0,1970.0,99000,67.9,146.0,170.0,Tonga,Monarchy,Taufa'ahau Tupou IV,3334.0,TO
Tuvalu,TuV,Oceania,Polynesia,26.0,1978.0,12000,66.3,6.0,NaN,Tuvalu,Constitutional Monarchy,Elisabeth II,3424.0,TV
uganda,uGA,Africa,Eastern Africa,241038.0,1962.0,21778000,42.9,6313.0,6887.0,uganda,Republic,Yoweri Museveni,3425.0,uG
united States Minor Outlying Islands,uMI,Oceania,Micronesia/Caribbean,16.0,NaN,0,NaN,0.0,NaN,united States Minor Outlying Islands,Dependent Territory of the uS,George W. Bush,NaN,uM
Vanuatu,VuT,Oceania,Melanesia,12189.0,1980.0,190000,60.6,261.0,246.0,Vanuatu,Republic,John Bani,3537.0,Vu
Wallis and Futuna,WLF,Oceania,Polynesia,200.0,NaN,15000,NaN,0.0,NaN,Wallis-et-Futuna,Nonmetropolitan Territory of France,Jacques Chirac,3536.0,WF
Samoa,WSM,Oceania,Polynesia,2831.0,1962.0,180000,69.2,141.0,157.0,Samoa,Parlementary Monarchy,Malietoa Tanumafili II,3169.0,WS
Zambia,ZMB,Africa,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162.0,ZM
Zimbabwe,ZWE,Africa,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068.0,ZW

In [22]:
#Filtro not
filtro91=df[~(df["continent"]=="Africa") & ~(df["head_of_state"]== "Elisabeth II")]
filtro91
#Todos los datos que no sean del continente de √Åfrica  y que la cabeza de estado no fuera Elisabeth II

,code,continent,region,surface_area,independence_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
name,,,,,,,,,,,,,,
Aruba,ABW,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Willem-Alexander,129.0,AW
Afghanistan,AFG,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
Albania,ALB,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqiperia,Republic,Rexhep Mejdani,34.0,AL
Andorra,AND,Europe,Southern Europe,468.0,1278.0,78000,83.5,1630.0,NaN,Andorra,Parliamentary Coprincipality,NaN,55.0,AD
Netherlands Antilles,ANT,North America,Caribbean,800.0,NaN,217000,74.7,1941.0,NaN,Nederlandse Antillen,Nonmetropolitan Territory of The Netherlands,Willem-Alexander,33.0,AN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Vanuatu,VuT,Oceania,Melanesia,12189.0,1980.0,190000,60.6,261.0,246.0,Vanuatu,Republic,John Bani,3537.0,Vu
Wallis and Futuna,WLF,Oceania,Polynesia,200.0,NaN,15000,NaN,0.0,NaN,Wallis-et-Futuna,Nonmetropolitan Territory of France,Jacques Chirac,3536.0,WF
Samoa,WSM,Oceania,Polynesia,2831.0,1962.0,180000,69.2,141.0,157.0,Samoa,Parlementary Monarchy,Malietoa Tanumafili II,3169.0,WS
Yemen,YEM,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780.0,YE
Yugoslavia,YuG,Europe,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,NaN,Jugoslavija,Federal Republic,Vojislav KoStunica,1792.0,Yu

In [25]:
#Convertir archivo filtrado a CSV
filtro1.to_csv("filtro1.csv")
filtro12.to_csv("filtro12.csv")
filtro21.to_csv("filtro21.csv")
filtro22.to_csv("filtro22.csv")
filtro31.to_csv("filtro31.csv")
filtro32.to_csv("filtro32.csv")
filtro_mix.to_csv("filtromix.csv")
filtrofresh.to_csv("filtrofresh.csv")
filtro4.to_csv("filtro4.csv")
filtro51.to_csv("filtro51.csv")
filtro52.to_csv("filtro52.csv")
filtro61.to_csv("filtro61.csv")
filtro71.to_csv("filtro71.csv")
filtro72.to_csv("filtro72.csv")
filtro81.to_csv("filtro81.csv")
filtro82.to_csv("filtro82.csv")
filtro91.to_csv("filtro91.csv")

In [33]:
#Descargar archivo filtrado en csv
from google.colab import files

files.download("filtro4")
files.download("filtro42")
files.download("filtro51")
files.download("filtro52")
files.download("filtro61")
files.download("filtro62")
files.download("filtro71")
files.download("filtro72")
files.download("filtro81")
files.download("filtro82")
files.download("filtro91")
files.download("filtro92")

FileNotFoundError: ignored